---
- name: "LAMP Configuration"
  hosts: all
  become: true 
  vars_files:
    - apache.var
    - mariadb.var
    - wordpress.var
  tasks:
    
    - name: "Apache - Installing Apache & php"
      yum:
        name:
          - httpd
          - php
        state: present
                 
    - name: "Apache - Copying Configuration File"
      template:
        src: httpd.conf.j2 
        dest: /etc/httpd/conf/httpd.conf
            
    - name: "Apache - Adding VirtaulHost Entry"
      template:
        src: virtualhost.conf.j2
        dest: /etc/httpd/conf.d/{{ httpd_domain }}.conf
      
    - name: "Apache - Creating Documentroot Directory"
      file:
        path: /var/www/html/{{ httpd_domain }}
        state: directory
        owner: "{{ httpd_owner }}" 
        group: "{{ httpd_group }}"
           
      
    - name: "Apache - Copying test.html & test.php"
      copy:
        src: "{{ item }}"
        dest: "/var/www/html/{{ httpd_domain }}"
      with_items:
        - test.php
        - test.html
        
            
    - name: "Apache - Restarting/Enabling Apache"
      service:
        name: httpd
        state: restarted
        enabled: true
            
    - name: "Mariadb-Server - Package Installing"
      yum:
        name:
          - mariadb-server
          - MySQL-python
          - php-mysql
        state: present
            
    - name: "Mariadb-Server - Service Restart/Enabling"
      service:
        name: mariadb
        state: restarted
        enabled: true
            
    - name: "Maiadb-Server - Updating Root Password"
      ignore_errors: true
      mysql_user:
        login_user: root
        login_password: ""
        name: "root"
        password: "{{ mysql_root }}"
        host_all: yes
            
    - name: "Mariadb-Server - removing anonymous users"
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root }}"
        name: ""
        state: absent
        host_all: yes
            
    - name: "Mariadb-Server - Creating database"
      mysql_db:
        login_user: root
        login_password: "{{ mysql_root }}"
        name: "{{ mysql_database }}"
        
    - name: "Mariadb-Server - Creating User"
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root }}"
        name: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
        priv: '{{ mysql_database }}.*:ALL'
            
    - name: "Wordpress - Downloading Archivefile"
      get_url:
        url: "{{ wordpress_url }}"
        dest: /tmp/wordpress.tar
            
    - name: "Wordpress - Extracting ArchiveFile"
      unarchive:
        src: /tmp/wordpress.tar
        dest: /tmp/
        remote_src: true
            
    - name: "Wordpress - Copying Contents To DocumentRoot"
      copy:
        src: /tmp/wordpress/
        dest: "/var/www/html/{{ httpd_domain }}"
        remote_src: true
        owner: "{{ httpd_owner }}"
        group: "{{ httpd_group }}"
            
    - name: "Worpress - Creating wp-config.php File"
      template:
        src: wp-config.php.j2
        dest: "/var/www/html/{{ httpd_domain }}/wp-config.php"
            
    - name: "Post-installation Restart"
      service:
        name: "{{ item }}"
        state: restarted
      with_items:
        - httpd
        - mariadb
        
    - name: "Post-Installation Cleanup"
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /tmp/wordpress.tar
        - /tmp/wordpress
